apiVersion: apps/v1
kind: Deployment
metadata:
  name: portti
  labels:
    app: portti
    tier: api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portti
  template:
    metadata:
      labels:
        app: portti
    spec:
      serviceAccountName: portti
      containers:
      - name: portti
        image: public.ecr.aws/kerminator/spring-portti:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
   