resources:
- deployment.yaml
- role.yaml
- rolebinding.yaml
- sa.yaml
- service.yaml
- configmap.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: portti
    app.kubernetes.io/name: portti
    app.kubernetes.io/part-of: otel-demo
    app.kubernetes.io/version: latest
