apiVersion: v1
kind: Service
metadata:
  name: portti
  labels:
    app: portti
spec:
  selector:
    app: portti
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080