apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: spring-portti
build:
  artifacts:
  - image: kerminator/spring-portti
    jib: {}
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
portForward:
- resourceType: service
  resourceName: portti
  port: 8080 # 
  localPort: 9000 # *Optional*
