apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: spring-portti
build:
  artifacts:
  - image: public.ecr.aws/kerminator/spring-portti
    jib: {}
portForward:
- resourceType: service
  resourceName: portti
  port: 8080
  localPort: 9000
profiles:
- name: local
  manifests:
    kustomize:
      paths:
      - manifests/overlays/local
  deploy:
    kubeContext: kind-kind
- name: playground
  manifests:
    kustomize:
      paths:
      - manifests/overlays/dev
  deploy:
    kubeContext: playground