apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: spring-portti
build:
  artifacts:
  - image: public.ecr.aws/kerminator/spring-portti
    jib: {}
portForward:
- resourceType: service
  resourceName: portti
  port: 8080
  localPort: 9000
profiles:
  - name: local
    build:
      local:
        push: false
    deploy:
      kustomize:
        paths: ["manifests/overlays/local"]
      kubeContext: rancher-desktop
  - name: playground
    deploy:
      kustomize:
        paths: 
          - manifests/overlays/dev
      kubeContext: playground
