server:
  shutdown: graceful
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #url-expression: "'http://'+serviceId"
    kubernetes:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  # endpoint:
  #   health:
  #     enabled: true
  #   restart:
  #     enabled: true
  #   info:
  #     enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE  
    org.springframework.cloud.loadbalancer: TRACE  
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    kubernetes:
        reload:
          enabled: true
          mode: polling
          period: 5000
        discovery:
          service-labels:
            route: true
