spring:
  main:
    banner-mode: "off"
  cloud:
    kubernetes:
      reload: 
        enabled: true
      discovery:
        all-namespaces: false
        service-labels:
          route: "true"

#management:
  #otlp:
  #  tracing:
  #    endpoint: http://otel-collector.otel-demo.svc.cluster.local:4318/v1/traces

logging:
  structured:
    format:
      console: ecs
